### PR TITLE
[copyq] New feature: search string in copyq history

### PR DESCRIPTION
**Pull request by BarbUk**
The search feature was not implemented yet.
It's now done !
Have a look at this beautiful gif
search-feature

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
@BarbUk you could add a meaingful decription. Maybe the time of the paste?

**Comment by BarbUk** [comment]
@ManuelSchneid3r nice suggestion, but after checking, I don't have that information in copyq.

**Comment by BarbUk** [comment]
I'll check if I can find something useful to use as a description.

**Comment by BarbUk** [comment]
Nothing useful. I can remove the item number, leaving no description:
image

**Comment by ManuelSchneid3r** [comment]
Maybe a comma separated list of contained mimetypes?

**Comment by BarbUk** [comment]
I filter the copyq history to only display text/plain so I can display that.
Is there a way to display picture in albert ?

**Comment by BarbUk** [comment]
The search function now return all matches !
So happy with the result :)

**Comment by BarbUk** [comment]
I have done several tests, and the description that work the best for me is:
image

For long string, I can view more information that way.

I had a strange bug with 16+ items displayed, the output of the plugin was sorted by albert (like when you had "id" on items), so I changed the default output to only 15 items.

**Comment by zw963** [comment]
I like this feature,  it is awesome for albert to support bash script external plugins, it always worked very well.

I am no see any advantage when try with python plugin, it always not work for a non python guys like me, 
not any linux distribution bundled with python3 (I guess), and so many distro link /usr/bin/python to `pythonoo 2.7`,  this cause CopyQ.py not worked completely ... :(

e.g.  following is some issue about CopyQ python plugin: 

1.  https://github.com/albertlauncher/python/blob/master/CopyQ.py#L5
     ``import html`` is failed, it only worked in python 3.3
 2.  ``from shutil import which`` failed, it only worked with 3.3 too
3.  ``from albertv0 import *``, where is albertv0 ? for my current distro (Deepin 15.7)
      never see a file named: `albertv0.py`.


So, albert is awesome, I hope can keep working legacy external plugin to work,  
deprecate purl bash script, and only support python, i think this maybe not a 
good idea,  maybe we should revert those commit, to let non-python guys like me
can choose external to work.

Thanks.

**Pull request merged**
