### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marek-mazur**
fix path

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Makes sense on my system the  .local/share/albert existed already. Does git create parent dirs?

**Comment by marek-mazur** [comment]
Yes, it does.

**Comment by ManuelSchneid3r** [comment]
Why have you closed this PR?

**Comment by marek-mazur** [comment]
Sorry.. i have pushed extension to my master branch. And I created new pull request instead of changing title of this one. Here it is: https://github.com/albertlauncher/external/pull/6

**Pull request closed without merging**
