### PR TITLE
External plugin for http://szotar.sztaki.hu

### PR DESCRIPTION
**Pull request by kissgyorgy**
An external plugin for quick word lookup for the "Sztaki szótár" dictionary.

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
I am not sure if this makes sense to pull in the official repo. The official repo is for, let me call it mainstream, extensions. What is "Sztaki szótár"?

**Comment by kissgyorgy** [comment]
Yes, at first I hesitated a bit, but I thought two things:
- There is no other collection of external plugins for Albert that I know of. You should have a forum or some place where it is easy to submit these. Alfred has a community forum, where members can share such plugins.
- Sztaki is high quality dictionary, developed by university students and general enough to be useful for others. We use it primarily in Hungary, but has other languages too like German, English, French, etc...

**Comment by ManuelSchneid3r** [comment]
Okay cool. Yes I was thinking of some mechanism like the pluginsystem of atom. But the external extension is still a prototype. I am still not satisfied with the integration in the core and the fact that they are explicitly startet each time. 

So is a search engine? I ask because the websearch extension is there for services that are started externally by a query in a url. Or does it have a web api and provide items? (Sorry i am on my phone atm)

**Comment by kissgyorgy** [comment]
> So is a search engine? I ask because the websearch extension is there for services that are started externally by a query in a url. Or does it have a web api and provide items? (Sorry i am on my phone atm)

It could be used as a search engine, but I found an AJAX API (sort of) and the results can be show "real-time":
image

**Comment by ManuelSchneid3r** [comment]
This kind of extensions has been deprecated a while ago now. I will close this pull request. You can still port this extension to python, which is even simpler to use.

**Pull request closed without merging**
